### ISSUE TITLE
Vertically stacked PICT v1

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#41]
I have a PICT v1 file: https://telparia.com/fileFormatSamples/image/pict/5_clamsh.ell

Deark extracts it as 18 separate images, each one a horizontal slice of the image, like:
![004](https://user-images.githubusercontent.com/81436/152664156-9168a8a4-1b95-4174-be49-5c45df58ec65.png)

If you stack all 18 images vertically on top of each other you get what appears to be the original version:
![combined](https://user-images.githubusercontent.com/81436/152664163-0e9d4552-1c6a-4abc-a60d-d79280a0e165.png)

I don't know much about the PICT format, but is there information embedded in the file that denotes how the sub-images should be laid out? Is it possible for deark to auto-stack them when the file states this and then output just a single image?

**Comment by Sembiance** [comment]
Here are two additional sample files that exhibit this behavior:
https://telparia.com/fileFormatSamples/image/pict/bbq
https://telparia.com/fileFormatSamples/image/pict/2kangaro.o

I can provide more if needed.

**Comment by jsummers** [comment]
A PICT file can contain any number of bitmaps, each with a specified position, size, and who knows what other attributes.

I've seen a few PICT files that are "tiled" like this. No easy solution that I can see.

Fully rendering a vector graphics image is out of scope for Deark. (Maybe try LibreOffice or ImageMagick.) It wouldn't necessarily solve the problem, anyway, since what we might want is the original, pre-processed, image(s).

Using heuristics to stitch together bitmaps that seem to belong together is possible, I'm sure, but not really something I want to try.

**Comment by Sembiance** [comment]
Ahh, gotcha. Any chance an option could be added to deark to output the position/size metadata for each image? Then I can stitch them together externally. If not, no worries.

**Comment by jsummers** [comment]
Well you can get it with the -d option, in the "dstRect" lines:
```
DEBUG:   dstRect: (0,0)-(576,42)
DEBUG:   dstRect: (0,42)-(576,84)
DEBUG:   dstRect: (0,84)-(576,126)
...
```

As for for something more robust, I've considered some ideas, such as putting the geometry in the filename, or in a PNG 'caNv' chunk when possible. But I'm not planning to do anything at this point. It doesn't seem worth the trouble. Note that I wouldn't want a PICT-specific feature -- it would have to work for all applicable formats.
