### ISSUE TITLE
PICT images with unsupported opcodes

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#65]
Came across a PICT file [PICT_137.zip](https://github.com/jsummers/deark/files/13762767/PICT_137.zip) that deark doesn't support. Looks like it uses a bunch of `PnPat` opcode calls which deark doesn't yet handle.
I don't know how difficult it would be to add support for that opcode, but it would be awesome if deark handled it because I couldn't find any other linux programs that handle it and only 2 windows programs:  QT Pic Viewer and Corel Photo Paint
In the attached zip is the original .pict and a .png of what QT Pic Viewer generates.

**Comment by Sembiance** [comment]
Both look like drawing routines, so I'm not sure if that's beyond the scope of deark or not.

The PICT `PnPat` opcode probably operates similar to the same named QuickDraw routine, documented around page 163 in the Inside Macintosh Volume 1: https://telparia.com/wip/Inside_Macintosh_Volume_I_1985.pdf

I found a few references to OvSize via Google with the search terms: mac "PICT" format book "ovsize"

**Comment by jsummers** [comment]
Both the PICT_137 and PICT_500 files seem to use only vector graphics, plus some custom extensions (stored in LongComment items) that do who-knows-what if you load them into exactly the right software.

There's not really anything that Deark can do with them, since it doesn't really support interpreting vector graphics.

(Well, the PnPat items probably contain an 8x8-pixel image that Deark could be made to extract, but that's not what you're looking for anyway. And Deark could support more opcodes in its debug info.)

PnPat sets the pen pattern, and I think OvSize configures how rounded rectangles will be drawn.

I had some success opening the files with Scribus and LibreOffice Draw, though it looks like there are some issues, and the custom extensions aren't supported.

**Comment by Sembiance** [comment]
Ahh gotcha, that's about what I figured. They open just fine in the Quicktime Picture Viewer, so I'll use that for now, thanks for creating deark!
