### ISSUE TITLE
Odd PCX Files

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#79]
I've encountered a group of odd PCX files: [oddPCX.zip](https://github.com/jsummers/deark/files/15504320/oddPCX.zip)
They are all 1-bit black and white images.
**Nothing** is able to convert them, _EXCEPT_ for [Konvertor](http://fileformats.archiveteam.org/wiki/Konvertor) but it only converts 'half' of the image.

In the attachment, the original pcx files are in `pcx` and the output from konvertor is in `konvertor`. Also in there are some `thumb` images that show you what the image is supposed to look like and also an `index.txt` that lists some info about the files.

These were discovered on this CD: https://discmaster.textfiles.com/browse/101/1-57176-053-9_2000_True_Type_Fonts_Clip_Art_Images_1994.iso/flowers

If deark were able to add support for this format, it would be the only converter I know of that can handle them.

**Comment by jsummers** [comment]
Thanks for the files. I don't think they're valid, but I'll add a workaround so that Deark can handle them. At worst, there could be a few extra columns of garbage/padding at the right edge of the image.

The issue is that the image's width is labeled incorrectly. There's an easy workaround that will work for these particular examples. I just haven't decided if I want to make it smarter than that.
